friendly_name = "Name you actually want to display"
#TODO (OS): Add some kind of way to track the git commit fingerprint

[target]
#default target
root="../../Relative/Path/To/Thing"
    [target.osx]
    #target configuration name
    #these vars shadow parents if configuration is specified
    root="/Some/Absoulte/Path"