"""Consts for Tacklebox"""
BAIT_FILE_NAME = ".tacklebait"
USER_CONFIG_FOLDER_NAME = ".tacklebox"
USER_CONFIG_FILE_NAME = ".tackleboxconfig"
BACKUP_DIR_NAME = ".tackleback"
CONFIG_EXTENSION_CURRENT = ".current"
USER_CONFIG_HOME = "~"
VERSION = "0.1"
