# User Config Schema
# all labels are lowercase.
version = "0.1"

[repo]
active= 'main'

    [repo.main]
    root='C:\Users\omer\My_Tacklebox'
    type="git"

[bait]
    [bait.home]
    # Only put in this list stuff that should be destroyed when the setup is cleaned
    # Upon Removal, Tacklebox will visit every path and delete only the leaf
    # (file or last folder)
    # Baits grabbed locally will by default leave this list empty.
    paths_created = [
    'C:\Absolute\Path\1',
    'C:\Absolute\Path\2'
    ]
